Repository AY2425S2-CS2103T-F13-2/tp, pull requests merged in 2025-04, with the labels that each got.

#135 Fix model diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High

#175 Added Pastry Name as mandatory to prevent empty orders
  src/main/java/powerbake/address/logic/parser/AddOrderCommandParser.java
Labels: alpha-bug

#177 Fix duplicate pastry
  src/main/java/powerbake/address/logic/Messages.java
  src/main/java/powerbake/address/logic/commands/AddOrderCommand.java
Labels: alpha-bug

#196 Update UG features and command summary
  docs/UserGuide.md
  docs/images/commands/editCommand1.png
  docs/images/commands/editCommand2.png
  docs/images/commands/editCommand3.png
  docs/images/commands/editCommand4.png
Labels: type.Documentation

#212 Fix duplicate name for edit name command
  src/main/java/powerbake/address/logic/parser/EditCommandParser.java
Labels: type.Bug, alpha-bug

#214 Add check for address length and testcases.
  src/main/java/powerbake/address/logic/parser/ParserUtil.java
  src/main/java/powerbake/address/model/person/Address.java
  src/test/java/powerbake/address/model/person/AddressTest.java
Labels: alpha-bug

#215 Add command consistency and add pastry quantity validation
  src/main/java/powerbake/address/commons/util/StringUtil.java
  src/main/java/powerbake/address/logic/commands/AddPastryCommand.java
  src/main/java/powerbake/address/logic/parser/AddOrderCommandParser.java
  src/main/java/powerbake/address/logic/parser/ParserUtil.java
  src/test/java/powerbake/address/commons/util/StringUtilTest.java
Labels: alpha-bug

#222 Fix edit client tags
  src/main/java/powerbake/address/logic/commands/EditCommand.java
  src/main/java/powerbake/address/logic/parser/EditCommandParser.java
Labels: type.Bug, alpha-bug

#228 Add test cases to the DG
  docs/DeveloperGuide.md
Labels: alpha-bug

#232 Fix minor typos
  src/main/java/powerbake/address/logic/commands/EditCommand.java
Labels: type.Bug, alpha-bug

#315 Fix prefixed whitespace before command
  src/main/java/powerbake/address/logic/parser/AddressBookParser.java
Labels: type.Bug

#339 Fix edit pastry name
  src/main/java/powerbake/address/model/pastry/Pastry.java
Labels: type.Bug

#336 Fix add order command message PASTRY_NAME to follow UG
  src/main/java/powerbake/address/logic/commands/AddOrderCommand.java
Labels: type.Bug
