Repository AY2425S2-CS2103T-F13-2/tp, pull requests merged in 2025-03, with the labels that each got.

#96 Add 'add client' and 'add pastry' commands in the UG
  docs/UserGuide.md
  docs/images/addclient1.png
  docs/images/addclient2.png
  docs/images/addpastry1.png
  docs/images/addpastry2.png
Labels: type.Documentation

#94 Add changes to the Storage Section of the User Guide
  docs/UserGuide.md
Labels: type.Documentation

#95 Update UG with introduction and navigation guide.
  docs/UserGuide.md
  docs/images/tutorial/pageNavHidden.png
  docs/images/tutorial/pageNavShown.png
  docs/index.md
Labels: type.Documentation

#97 Add UG commands section
  docs/UserGuide.md
  docs/images/commands/deleteCommand1.png
  docs/images/commands/deleteCommand2.png
  docs/images/commands/deleteCommand3.png
  docs/images/commands/deleteCommand4.png
  docs/images/commands/viewCommand1.png
  docs/images/commands/viewCommand2.png
  docs/images/commands/viewCommand3.png
Labels: type.Documentation

#99 Update UG command section
  docs/UserGuide.md
Labels: type.Documentation

#101 Update UG and DG glossary
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#103 Enable Assertions
  build.gradle
  src/main/java/powerbake/address/Main.java
Labels: type.Task, priority.High

#127 Update help command URL
  src/main/java/powerbake/address/ui/common/HelpWindow.java
Labels: type.Task, priority.Medium

#128 Update DG architecture sequence model
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: priority.Medium, type.Documentation

#118 Update parser class diagram
  docs/diagrams/ParserClasses.puml
Labels: type.Documentation

#125 Update DG UI diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation

#131 Update DG API Links
  docs/DeveloperGuide.md
Labels: type.Documentation
